#include<stdio.h>#include<conio.h>#include<string.h>
#include<stdlib.h>
voidmain()
{FILE*fp;
inti,addr1,l,j,staddr1;
charname[10],line[50],name1[10],addr[10],rec[10],ch,staddr[10];1
//clrscr();
printf("enterprogramname:");
scanf("%s",name);
fp=fopen("abssrc.txt","r");
fscanf(fp,"%s",line);
for(i=2,j=0;i<8,j<6;i++,j++)
name1[j]=line[i];
name1[j]='\0';
printf("namefromobj.%s\n",name1);
if(strcmp(name,name1)==0)
{do
{
    fscanf(fp,"%s",line);
    if(line[0]=='T')
    {
        for(i=2,j=0;i<8,j<6;i++,j++)
        staddr[j]=line[i];
        staddr[j]='\0';
        staddr1=atoi(staddr);
        i=12;31.while(line[i]!='$')
        {
            if(line[i]!='^')
            {
                printf("00%d\t%c%c\n",staddr1,line[i],line[i+1]);
                staddr1++;
                i=i+2;
                }
                elsei++;
                }
                }
                elseif(line[0]='E')
                fclose(fp);
                }while(!feof(fp));
            }
                getch();
}